dist: xenial
sudo: required
language: python
cache: pip
python:
- '3.7'
jdk:
- oraclejdk8
before_install:
- npm install -g bower
- bower install
- wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
- echo 'deb https://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
- sudo apt-get update
- sudo apt-get install neo4j=1:3.5.3
- sudo systemctl enable neo4j
- sudo systemctl start neo4j
- sleep 8
- sudo neo4j-admin set-initial-password neo4j
- sleep 1
install:
- pip install -r requirements/dev.txt
before_script:
- python manage.py collectstatic
script:
- python manage.py test