dist: xenial
sudo: required
language: python
cache: pip
python:
- '3.7'
services:
- neo4j
before_install:
- npm install -g bower
- bower install
- sudo service neo4j stop
- sudo sed -i 's|dbms.security.auth_enabled=false|dbms.security.auth_enabled=true|g' /etc/neo4j/neo4j.conf
- sudo service neo4j start
install:
- pip install -r requirements/dev.txt
before_script:
- python manage.py collectstatic
script:
- python manage.py test