dist: xenial
sudo: required
language: python
python:
- '3.7'
before_install:
- npm install -g bower
install:
- pip install -r requirements/dev.txt
before_script:
- bower install
- python manage.py collectstatic
script:
- python manage.py test
