# Generated by Django 2.2 on 2019-04-27 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringHistory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tweet_id', models.UUIDField()),
                ('delta_score', models.FloatField()),
                ('cumulative_score', models.FloatField()),
                ('type', models.CharField(choices=[(post.models.ScoringHistoryType('POST_WRITE'), 'POST_WRITE'), (post.models.ScoringHistoryType('POST_LIKE'), 'POST_LIKE'), (post.models.ScoringHistoryType('POST_COMMENT'), 'POST_COMMENT')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
